name: app

services:
  db:
    build: ./db
    networks:
      - app-net
    ports:
      - 3306:3306

  frontend: 
    depends_on:
      - backend
    build: ./frontend
    networks:
      - app-net
    ports:
      - 3000:3000

  backend:
    depends_on:
      - db
    build: ./backend
    networks:
      - app-net
    ports:
      - 5050:5050

networks:
  app-net:
    driver: bridge